### ISSUE TITLE
Error in { : task 1 failed - "subscript out of bounds"

### ISSUE THREAD

**Issue by zhengdafangyuan** [CSOgroup/CALDER2#10]
First of all, thank you for creating CALDER2! It's an invaluable tool for 3D genome analysis. 

I have installed the CALDER2 using `remotes::install_github("CSOgroup/CALDER2")` 
# CALDER2 Error when Calling Compartments

`
contact_mat_file <- "./GM12878_chr1_50kb_ob.txt.gz"
save_dir <- "./chr1_50kb"
binsize <- 50000
chrs=c("1")
CALDER(contact_file_dump=contact_mat_file, 
			chrs=chrs, 
			bin_size=binsize,
			genome='hg38',
			save_dir=save_dir,
			save_intermediate_data=FALSE,
			sub_domains=FALSE)
`
This results in the error:
`
[ 1 ] Begin process contact matrix and compute correlation score at: 2023-09-01 12:30:53 
[ 1 ] Begin process contact matrix and compute correlation score at: 2023-09-01 12:30:53 
Error in { : task 1 failed - "subscript out of bounds"
`

I have attached the contact matrix file I am using. Please let me know if I am missing something in my usage of CALDER() or if there is an issue with processing this contact matrix. Thanks for your help troubleshooting!
[GM12878_chr1_50kb_ob.txt.gz](https://github.com/CSOgroup/CALDER2/files/12494329/GM12878_chr1_50kb_ob.txt.gz)

**Comment by zhengdafangyuan** [comment]
`
contact_mat_file <- "./GM12878_chr1_50kb_ob.txt.gz"
save_dir <- "./chr1_50kb"
binsize <- 50000
chrs=c("1")
CALDER(contact_file_dump=contact_mat_file, 
			chrs=chrs, 
			bin_size=binsize,
			genome='hg38',
			save_dir=save_dir,
			save_intermediate_data=FALSE,
			sub_domains=FALSE)

[ 1 ] Begin process contact matrix and compute correlation score at: 2023-09-01 12:46:56 
[ 1 ] Begin process contact matrix and compute correlation score at: 2023-09-01 12:46:56 
Error in { : task 1 failed - "subscript out of bounds"
`

**Comment by YuanlongLiu** [comment]
I think you need to store *contact_mat_file* into a list, and name it by
*chrs*. See the "Parameters" section for more details

*contact_mat_file = as.list(contact_mat_file)*
*names(contact_mat_file) = chrs*

Let me know whether this solves the problem.

Best,
Yuanlong

**Comment by zhengdafangyuan** [comment]
Yes, it's ok now. Thanks!
