### ISSUE TITLE
Task 70 failed - "'k' must satisfy 0 < k < nrow(A)"

### ISSUE THREAD

**Issue by Bennibraun** [CSOgroup/CALDER2#11]
Hi, I'm getting an error when trying to run Calder2 (installed via bioconda) on a .hic file.

Here is a snippet of the output when it fails:

```
[ Y ] Begin process contact matrix and compute correlation score at: 2023-09-12 11:15:59.690633 
[ Y ] Finish process contact matrix and compute correlation score at: 2023-09-12 11:16:00.959082 
[ Y ] Begin compute compartment domains and their hierachy at: 2023-09-12 11:16:00.963438 
[ Y ] Computing compartments
Error in { : task 70 failed - "'k' must satisfy 0 < k < nrow(A)"
Calls: CALDER -> %dopar% -> <Anonymous>
Execution halted
```

Here is my full R script:
```R
library(CALDER)	
chrs = c(1:22,"X","Y")

save_dir = "/path/to/calder_output"
hic_file = '/path/to/matrix.hic'

CALDER(contact_file_hic=hic_file, 
			chrs=chrs, 
			bin_size=10E3,
			genome='hg19',
			save_dir=save_dir,
			save_intermediate_data=TRUE,
			n_cores=4,
			sub_domains=TRUE)
```

Everything looks good until it finishes computing all the compartments. Is there something wrong with my script, or is this a bug in Calder?

**Comment by Bennibraun** [comment]
I've found the issue: my HiC matrix has almost no contacts in the Y chromosome, so it fails to compute compartments. I'm not sure where exactly the error occurs, so maybe a step to check whether a matrix is too sparse would allow for a more helpful error message. From now on I'm just excluding chrY from the analysis.

**Comment by YuanlongLiu** [comment]
It should be related to chrY, which is not included in the hg19
implementation. In addition, the reference compartment used by Calder does
not include chrY. So an additional feature_track will be needed if you want
to analyze chrY.

Let me know if you have any other questions.
