### ISSUE TITLE
The R package of "maptools"  is not available from 10,2023

### ISSUE THREAD

**Issue by Wan9299** [CSOgroup/CALDER2#12]
Can you replace it with something else?

**Comment by YuanlongLiu** [comment]
There is no maptools used in Calder

**Comment by Wan9299** [comment]
but, maptools is needed here? now I do not install CALDER online normally.
![image](https://github.com/CSOgroup/CALDER2/assets/149647409/934d7b43-8f85-4570-9926-b75cb1c7f254)

**Comment by YuanlongLiu** [comment]
Have removed `maptools` from DEPENDANCIES, sorry for inconvenience
