### ISSUE TITLE
how to generate a custom feature_track  file?

### ISSUE THREAD

**Issue by kuangzhuoran** [CSOgroup/CALDER2#5]
I don't really understand the "chr start end score", especially the “score"

This refers to which regions of the genome 
and what characteristic values of these regions are represented by the "score" values

**Comment by YuanlongLiu** [comment]
Please refer to the readme for detailed description about `feature_track`. In the Usage section, an example of `feature_track` is also provided.

'which regions of the genome': the `feature_track` should cover as many as possible of the genomic regions you aim for running CALDER

**Comment by kuangzhuoran** [comment]
Thanks a lot~

I get it, I need to count the genome-wide gene density
So the meaning of the feature_track file can be the number of genes in a given interval
I'm considering genome-wide sliding window statistics, and the window size would be the same as the resolution for calculating the AB compartment

chr  startbp  endbp  gene_density
 1     0           40000   130
 1     40000   80000    54

I noticed that your description of this document mentioned:” Note that this information will not alter the hierarchical compartment/TAD structure“.. 
What is the purpose of this file, which was not needed in your previous version, CALDER1?
