### ISSUE TITLE
Error in { :    task 22 failed - "File is empty:"

### ISSUE THREAD

**Issue by zzhoujialu** [CSOgroup/CALDER2#8]
Hi, thank you for developing this amazing tool. 
I encounter the following errors at the resolution of 100k and I have no idea why it happened:

### task 22 failed - "File is empty: /tmp/Rtmpu3ACnD/file813b736a80db"

intermediate_data dir was completed while sub-compartments dir was not built.

Do you have any idea of what could be causing the error?
Looking forward to hearing from you!
kalo

**Comment by lucananni93** [comment]
Please specify:

1. How you run the tool: which command did you use and with which parameters
2. The kind of data you are using: hic or cool files, genome assembly, etc...

**Comment by zzhoujialu** [comment]
Hi, I found the reason. KR normalization failed to converge at one chrom...  I applied the VR normalization and made it. 
Thank you :)

**Comment by zzhoujialu** [comment]
Hi, I found the reason. KR normalization failed to converge at one chrom...  I applied the VR normalization and made it. 
Thank you :)
