### ISSUE TITLE
normalizations other than KR

### ISSUE THREAD

**Issue by brauliobonilla** [CSOgroup/CALDER2#9]
Hi, 

I am trying to use CALDER with my .hic files but they don't have the KR normalization. Is there a way to tell CALDER to use a different one?

Thank you!

**Comment by YuanlongLiu** [comment]
Hi,

CALDER2 will try KR normalization first. If no KR, then VC or VC_SQRT.
Which normalization do you have in your .hic? You can also convert the .hic
file into three-column dump format using the normalization you specified,
then run CALDER by assign your file to the *contact_file_dump* parameter

Best,
Yuanlong

**Comment by brauliobonilla** [comment]
Hi Yuanlong,
Thank you for your response. I certainly have VC. Yes, the dump alternative is working for me, it was just more convenient to use the .hic. I used juicer2.0 to build these files (did they change the location of the norms in the file?). 
BTW this is what I m getting: Error : File did not contain KR normalization vectors for one or both chromosomes at 500000 BP.
Error in { : task 1 failed - "argument is of length zero"

Best,
Braulio

**Comment by brauliobonilla** [comment]
Hi Yuanlong,

Thank you. I am sharing [this folder](https://pitt-my.sharepoint.com/:f:/g/personal/brb148_pitt_edu/EnSRarndTWZKoFgugv5TCXMBplKq6PHd2rO1HT27NbWLUw?e=CpWWcJ), it has a .hic file, the code that I used for dump with this .hic (VC and SCALE give files but KR produces an empty file), the dumped files, and the R code that I used with CALDER2 

Let me know if there is something wrong

Thanks,

Braulio

**Comment by YuanlongLiu** [comment]
Hi Kevin, there seems a problem with this ENCFF364UZU.hic file, since I cannot open it with Juicerbox (1.11.08). Also I am not able to straw it: strawr::straw("KR", 'ENCFF364UZU.hic',  'chr22',  'chr22', "BP", 10000). Can you check whether you observe the same?

Best,
Yuanlong

**Comment by MoreauK** [comment]
Hi Yuanlong,
Yes I observed the same:
> strawr::straw("KR", 'ENCFF364UZU.hic', 'chr22', 'chr22', "BP", 10000)
Erreur : File did not contain KR normalization vectors for one or both chromosomes at 10000 BP.

Super weird... I tried with another dataset downloaded from GEO, and it doesn't work either (GSE66733).

Best,
Kevin

**Comment by YuanlongLiu** [comment]
Maybe you can use the dump command to save the contacts then pass to CALDER
use the contact_file_dump parameter
